# print("*******************")
# print("*******************")
# print("*******************")
# print("*******************")
# print("--------------------")
# print("*******************")
# print("*                 *")
# print("*                 *")
# print("*******************")
# print("--------------------")
# print("*")
# print("**")
# print("***")
# print("****")
# print("--------------------")

# print((512-282)/(47*48+5))

# print("--------------------")
# num=eval(input("Enter a number:"))
# print("The square of ",num," is ",num*num,".",sep="")

# print("--------------------")
# num=eval(input("Enter a number:"))
# print(num,2*num,3*num,4*num,5*num,sep="---")
# print("--------------------")
# weight=eval(input("Enter the weight in kilograms:"))
# print("Weight in Pounds:",weight*2.2)
# print("--------------------")
# meal_price=eval(input("PLease enter the meal cost:"))
# percent_tip=eval(input("PLease enter the percent tip:"))

# print("Meal price=", meal_price)
# print("Tip=", meal_price*percent_tip/100)
# print("Total bill=", meal_price+(meal_price*percent_tip*100) )
